name: aaaaaaaaaa

on:
  push:
    branches:
      - master

jobs:
  update_draft_release:
    name: Draft release
    runs-on: ubuntu-latest

    steps:
      - uses: ThatGamerBlue/release-drafter@36aa72a73bfbf01e5cb7369368566f267ac367db
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
