name: aaaaaaaaaa

on:
  push:
    branches:
      - master

jobs:
  update_draft_release:
    name: Draft release
    runs-on: ubuntu-latest

    steps:
      - uses: ThatGamerBlue/release-drafter@cbc9b954ff68cd9622734324ed896da6ef73735e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
