name: aaaaaaaaaa

on:
  push:
    branches:
      - master

jobs:
  update_draft_release:
    name: Draft release
    runs-on: ubuntu-latest

    steps:
      - uses: ThatGamerBlue/release-drafter@f7dc997dbcb32c60d79470374476d374e241b380
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
