name: aaaaaaaaaa

on:
  push:
    branches:
      - master

jobs:
  update_draft_release:
    name: Draft release
    runs-on: ubuntu-latest

    steps:
      - uses: ThatGamerBlue/release-drafter@90317026b637adb5710dd1df3942691057745235
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
