name: aaaaaaaaaa

on:
  push:
    branches:
      - master

jobs:
  update_draft_release:
    name: Draft release
    runs-on: ubuntu-latest

    steps:
      - uses: ThatGamerBlue/release-drafter@71e9fe091fb9ee83a3ff0a13cf2cd8ef9b5c7c79
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
