name: aaaaaaaaaa

on:
  push:
    branches:
      - master

jobs:
  update_draft_release:
    name: Draft release
    runs-on: ubuntu-latest

    steps:
      - uses: ThatGamerBlue/release-drafter@9dfdef329b5101b16484bf60a3e71dc6839b9109
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
