name: aaaaaaaaaa

on:
  push:
    branches:
      - master

jobs:
  update_draft_release:
    name: Draft release
    runs-on: ubuntu-latest

    steps:
      - uses: ThatGamerBlue/release-drafter@v5.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
