name: aaaaaaaaaa

on:
  push:
    branches:
      - master

jobs:
  update_draft_release:
    name: Draft release
    runs-on: ubuntu-latest

    steps:
      - uses: ThatGamerBlue/release-drafter@f7037155b6ba182be60e2c9eb8cd817dfe67a65d
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
